CREATE DATABASE dbweb4;

CREATE TABLE album(
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	text VARCHAR(100) NOT NULL,
	photo_id INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (photo_id)
	REFERENCES photos (id)
);

CREATE TABLE photo(
	id INT(11) NOT NULL AUTO_INCREMENT,
	tanggal DATE,
	title VARCHAR(100) DEFAULT NULL,
	text TEXT,
	post_id INT(11) DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (post_id)
	REFERENCES post (id)
);

CREATE TABLE post(
	id INT(11) NOT NULL AUTO_INCREMENT,
	date DATE,
	slug VARCHAR(25) DEFAULT NULL,
	title VARCHAR(100) DEFAULT NULL,
	text TEXT,
	cat_id INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (cat_id)
	REFERENCES category(id)
);

CREATE TABLE category(
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR (100) NOT NULL,
	text VARCHAR (100) NOT NULL,
	PRIMARY KEY (id)
);